### ISSUE TITLE
Programme does not accept txt files as -a parameter inputs

### ISSUE THREAD

**Issue by mhdshk-1** [GfellerLab/MixMHC2pred#11]
Hi!

I'm just running into an issue where I'm trying to predict binding for all available HLA alleles. I can't simply provide all of the allele names as parameters in command line because I run into the ~8000 character limit. I have therefore provided a path to a file containing the names of all of the HLA alleles separated by a space, as recommended by the documentation. However the programme refuses to run and returns the following error message:

`The allele(s) 'C:\Me\alleles.txt' aren't defined in 'C:\Users\Me\MixMHC2pred-2.0/PWMdef/',  cannot perform the computations.`

There is no clear reason for this to occur, the txt is correctly formatted using the approved names from the human alleles list file, and the encoding is UTF-8. Are there any other ways to run binding predictions for all alleles in the programme's definitions?

Thank you.

**Comment by jracle85** [comment]
Hello,

I'm sorry to hear that you have issues running MixMHC2pred.

Please note that the alleles can only be given in the command line, not in a file (I don't think that the documentation indicates that it is possible to use a txt file for the alleles and it would be an error if it did - (when we say *"also given in the files Alleles_list_xxx.txt in the corresponding PWMdef folders"*, it is to tell that the list of alleles that can be run with MixMHC2pred is given in this txt file, not that you could use such a txt file as an input for our tool)).

So if you really want to run MixMHC2pred for all alleles, you should try to split your runs into multiple ones (or maybe if you submit MixMHC2pred through a bash script this 8000 character limit isn't present?). Anyway, MixMHC2pred isn't really thought for running with so many alleles at a time, it may still take a long time to run it and you may run into memory issues (depending on the peptide list size as well). Concerning the timing, it shouldn't make a big difference if you run MixMHC2pred once for many alleles or multiple times with a single allele at a time (as we need anyway to repeat all computations for all alleles as returning the score of each allele when run with multiple alleles together).

I hope you'll manage to use MixMHC2pred for your task and that you'll obtain interesting and useful results.

Best regards,

Julien
