### ISSUE TITLE
How to distinguish strong and weak binder?

### ISSUE THREAD

**Issue by hxxhust163** [GfellerLab/MixMHC2pred#12]
Hi

Thanks for your work in MixMHC2pred. I have tried this tool and found it was very easy to use. Currently, I want to compare it with netMHCpanII, so I am writing to ask you how to distinguish the strong and weak binder in the output file. As you know, the netMHCpan indicates strong and weak binder by the value of rank.
Thanks very much!

Best regards
Xiaoxiang

**Comment by jracle85** [comment]
Hello,

The strongest binders have the lowest %Rank values. We don't indicate strong or weak binding as these limits are a bit arbitrary. Note also that our scores are scores of peptide presentation, not binding (binding is a very important part of this score, but other steps of antigen processing/presentation influence it).

If you still want to define peptides' "binding strength", similarly to NetMHCIIpan, you could likely define strong binders as those that have a %Rank < 1-2 and weak binders as those with %Rank < 10-20.

Best regards,

Julien
