### ISSUE TITLE
Trainning data for MixMHCIIpred

### ISSUE THREAD

**Issue by kcuong0503** [GfellerLab/MixMHC2pred#13]
hi,

Thank you for your work in MixMHC2pred. Now, I want to compare it with other tools. So I'm trying to find the training data set of this tool but can't find it. Can I have access to the training dataset?

**Comment by jracle85** [comment]
Hello,
you can find all the data used to train MixMHC2pred in Table S2 from our publication (https://www.cell.com/immunity/fulltext/S1074-7613(23)00129-2#supplementaryMaterial). In Table S1 from our publication you'll also find the full typing from each sample, which was additionally used when training the second neural network block (NN<sup>2</sup>) of our predictor as indicated in the STAR Methods.
Best regards,
Julien
