### ISSUE TITLE
Question on the use of MixMHC2pred webserver

### ISSUE THREAD

**Issue by winnieWei123456** [GfellerLab/MixMHC2pred#14]
Dear developer,

Hello, I encountered some issues while using MixMHC2pred webserver. For the first block, which is used to predict binding specificity, after entering an existing allele in the text box and clicking the "Predict Allele Specificities" button, the page displays "Cannot POST /alleles." It seems that an error has occurred. Additionally, the "List alleles" and "Help/FAQ" modules on your web server also do not open. When I click the corresponding buttons, no content is displayed.
![List alleles](https://github.com/GfellerLab/MixMHC2pred/assets/111028404/859e68f8-8d2e-4cff-989d-20d482cf3f52)
![cannot post](https://github.com/GfellerLab/MixMHC2pred/assets/111028404/aefd3175-1acc-4db1-9fce-e96044a00b81)

Looking forward to your reply.

**Comment by jracle85** [comment]
Dear WinnieWei,

I'm sorry to hear that you encountered an error with the server. I tried right now and I didn't have any issue.

Maybe the server was down for some time? Can you reproduce the error? If the error is still there, what navigator are you using? Which allele name do you enter in the field?

If the error is still there, you could try using the following direct address of the server: http://ec2-18-188-210-66.us-east-2.compute.amazonaws.com:4000

I hope it works. Best regards,

Julien

**Comment by winnieWei123456** [comment]
Dear Julien,


Hello. I apologize for the delay in responding to you. I tried the link you provided, but I still couldn't access it. However, I asked a colleague of mine for help, and they were able to use MixMHC2pred. It seems to be an issue with my computer. I will investigate further. Thank you very much for your response. As someone who is new to the field of immunopeptidomics peptides, I am thrilled to be able to communicate with an expert like you. Thank you so much~


Best regards,
Winnie Wei





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GfellerLab/MixMHC2pred"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月23日(星期五) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GfellerLab/MixMHC2pred] Question on the use of MixMHC2pred webserver (Issue #14)





 
Dear WinnieWei,
 
I'm sorry to hear that you encountered an error with the server. I tried right now and I didn't have any issue.
 
Maybe the server was down for some time? Can you reproduce the error? If the error is still there, what navigator are you using? Which allele name do you enter in the field?
 
If the error is still there, you could try using the following direct address of the server: http://ec2-18-188-210-66.us-east-2.compute.amazonaws.com:4000
 
I hope it works. Best regards,
 
Julien

**Comment by jracle85** [comment]
Hello Winnie Wei,

Good to see that it works at least on your colleague's computer. Maybe it is an issue with your internet browser, you could maybe try using Firefox or Chrome. And if you don't manage to make it work, you could also try using directly the standalone version, it should be easy to use as well (https://github.com/GfellerLab/MixMHC2pred/releases/latest).

Best,

Julien
