### ISSUE TITLE
regarding allele list

### ISSUE THREAD

**Issue by tianlt** [GfellerLab/MixMHC2pred#15]
Hello,

May I ask why allele list DRB is single but DPA/DPB or DQA/DQB are in pair? And if there is any option to input only DPB instead of the pair type for prediction? 

Thank you very much

**Comment by jracle85** [comment]
Hello,

We are doing this following the standard practice in the field. The reason for it is that DRA is an invariant chain with virtually a single allele for the whole population. On contrary DPA and DQA chains are variable and heterodimers formed by a given DPB and different DPA won't present exactly the same peptides; the information about DPA is therefore important (and similarly for DQ).

There is thus no option of only giving DPB as an allele. Note however that DPA1*01:03 (or DPA1_01_03 in our notation) is much more frequent in the population. If you don't know DPA, taking this allele as a proxy could thus be a decent approximation. For DQ the situation is more complex with no dominant allele (but some linkage disequilibrium could help imputing it from the rest of the haplotypes).

Best regards,

Julien

**Comment by tianlt** [comment]
Thank you for your detailed explanation Julien!
