### ISSUE TITLE
MixMHC2pred failed to predict some peptides

### ISSUE THREAD

**Issue by winnieWei123456** [GfellerLab/MixMHC2pred#16]
Dear developers:
      Hi!
      I am trying to run MixMHC2pred on some datasets consisting of  MS eluted ligands. However, some peptides yielded no results, only a row of NA. This is strange because all my inputs are common amino acids. I have attached a screenshot and my result file here. Hope you can shed some light on this issue, and why these peptides are not yielding any predictions.
![pic](https://github.com/user-attachments/assets/39c1653d-049b-4a2d-ad6f-49b716b31979)

[result.txt](https://github.com/user-attachments/files/16944748/result.txt)

**Comment by ili3p** [comment]
The peptide sequences are too long.

**Comment by winnieWei123456** [comment]
oh! I see. Thank you so much.
