### ISSUE TITLE
Interpretation of columns

### ISSUE THREAD

**Issue by BioinformaNicks** [GfellerLab/MixMHC2pred#4]
Dear author(s),

I am wondering the following:
MixMHCpred for class-I has both a Score_bestAllele and a %Rank_bestAllele that both give very different outputs.
MixMHC2pred for class-II has just a %Rank_best column and no real score.

We want to compare epitope presentation patterns of different proteomes based on your prediction tools, for both class-I and class-II. We would want to use a single metric for comparison. Would it be wise to compare %Rank's metrics?

Or am I missing a binding score for MixMHC2pred? I guess not considering you wrote the following in the paper:
"This binding score is then transformed to a percentile rank per peptide length by
comparing it to the score of 10’000 random human peptides of the same length, and
then further transformed to a global percentile rank by making that the top 1% random
human peptides follow the same peptide length distribution than the global peptide
length distribution observed in our HLA-II peptidomics data. Finally, when the score
among multiple alleles is requested, the score from each peptide is taken as its best
percentile rank among all the alleles"

**Comment by jracle85** [comment]
Hi,
First, sorry for the late response. It's been hard times with the Covid-19...
For both predictors, we would recommend to use the *%Rank_best* value. In both cases, this corresponds to a percentile score comparing the given peptide against random peptides.
The *Score_bestAllele* returned by MixMHCpred corresponds to a raw score, before comparison with random peptides, but it is generally assumed that a *%Rank* is better for a comparison between different alleles.
We currently don't return this score for MixMHC2pred because it is even harder to compare this value between different alleles and peptide lengths, so I preferred not to include it there so that people don't get confused about which value to use as *scores*.
Please note however that you shouldn't compare the *%Rank* from MixMHCpred to those from MixMHC2pred. The binding/processing for HLA class I and class II is quite different so the scores for class I and II aren't really comparable.
Best regards,
Julien

**Comment by BioinformaNicks** [comment]
Dear Julien,

First of all, no problem! I can imagine it's been busy and weird times, stay safe and healthy!
Thanks for your lengthy and thorough response, it is quite clear, however I still have a few questions if I may.

Generally what I want to do is predict strong binding epitopes for a set of alleles, of both class I and class II. Therefore, I have to use both the class-I and class-II tools. To define strong binding epitopes I would devise a 'relative' score by standardizing the metric (%Rank or Score, for example) by calculating it's score relative to the best score of a list of abundant human proteins. So it would be relative score = best score of human set / score of species I am interested in. I thought this would probably minimize any bias introduced by the difference in binding/processing for class-I and class-I, and therefore in tool metric? Thus, I would be able to determine for example whether a class-I or class-II seems to be more important in the immune response against this species.
Would you still advise against this?

**Comment by jracle85** [comment]
Hi,
I'm not sure to totally understand and that it fully makes sense.
First, I don't really understand your standardizing of the metric: the %Rank is already some kind of standardized value as it is compared against random peptides derived from the human proteomes (note that the protein abundance is however not taken into account into our predictors). So if you compare against a random set of most abundant human proteins or just a random set of human proteins, it shouldn't really change the results much - ok, you won't have a %Rank anymore with your standardization but maybe more a z-score.
And then it is very hard to tell just from the predicted values if the immune response would be more a class-I or class-II. For this, you'd need to have experimental data, not predictions. What our predictors are giving you, is more a prioritization of the best candidate epitopes. But as said above, it doesn't really make sense to compare predictions on class-I and -II: there are difference in expression levels of the various HLA classes (or also not all cells express HLA-II), also of binding affinities, processing pathways and recognition by the CD4/8 T cells. So it could be possible (but I don't have the answer for that), that for HLA-I you'd need a score of e.g. < 1% to be a potentially immunogenic peptide, while for class II, maybe a score of e.g. < 5% is sufficient (and many peptides with such scores will still be not immunogenic for other reasons).
If you can do experiments in your organisms of interest, I would thus better recommend to take the X best predicted peptides for HLA-I and the X best predictions for HLA-II and then see how many are immunogenic in both cases.
Cheers,
Julien
