### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by BioLaoXu** [GfellerLab/MixMHC2pred#6]
Dear developers ：
MixMHC2pred is a powerful tools for peptide prediction whith MHC2 alleles,but an error has occurred when i test the binary file,just like as follow:
![image](https://user-images.githubusercontent.com/13416926/89762430-01472700-db23-11ea-8f6d-fdd13d920a4f.png)
my linux system version is centos 6.5，so i would like to know the environment in which the tool works，look forward to your reply，thanks.

**Comment by jracle85** [comment]
Hello,

I'm sorry to hear that you couldn't run MixMHC2pred on your system.

I'm not an expert in Linux, but if I'm not wrong, it should work on linux starting from kernel version 3.2.0 (and yours is unfortunately 2.6.32).

From what I've seen, centos 6 is quite old and will come to an end of maintenance on November 30, 2020 ([https://en.wikipedia.org/wiki/CentOS](https://en.wikipedia.org/wiki/CentOS)). So I'd advice that you update to centos 8 (or at least 7) or some other linux version.

Best regards,

Julien

**Comment by BioLaoXu** [comment]
thanks very much，I will testing on the new system environment.
