### ISSUE TITLE
The method of obtaining random peptides

### ISSUE THREAD

**Issue by wt12318** [GfellerLab/MixMHC2pred#7]
Hi,

The paper had described the method to calculate `%Rank` : "This binding score is then transformed to a percentile rank per peptide length by comparing it to the score of 10,000 random human peptides of the same length". But I don’t understand how these random peptides were obtained, from randomly translating human genome regions into peptides ?

Thank you.

**Comment by jracle85** [comment]
Hello,

These are random peptides coming from known proteins, not random genome regions. We used human proteins annotated in uniprot, and randomly selected peptides from these proteins (considering all proteins, without taking into account the possibility that a protein isn't translated).

I hope this answer your question. Best wishes,

Julien

**Comment by wt12318** [comment]
Thanks for your answer.
