### ISSUE TITLE
How do we filter the large result?

### ISSUE THREAD

**Issue by gudeqing** [GfellerLab/MixMHC2pred#8]
Hi, is there any suggestion to do filtering of final result?

**Comment by jracle85** [comment]
Hello,

I'm not sure what kind of filtering you're asking about. But MixMHC2pred returns predictions for all of the inputted peptides, and usually we'll then be interested only by the peptides that had the best %Rank (0 is the best, 100 the worst). What threshold to use as best depends on what you're interested in, if you want a bigger or smaller list of peptides. Usually, values below 1 are good binders, but we can still find peptides bound to their respective HLA with scores of about 10.

After, other filtering options depend also on what you're studying. E.g. if a peptide is predicted to be a very good binder but you know that its protein of origin is not expressed in the given cell, then you wouldn't be able to find this peptide bound to the HLA in vivo.

Best regards,

Julien
