### ISSUE TITLE
Include raw prediction score in output

### ISSUE THREAD

**Issue by JonasNilsson1** [GfellerLab/MixMHC2pred#9]
Hi there,

Currently the program only outputs the percentile rank score for each peptide. Is it possible to include the raw prediction scores (i.e. the prediction between 0 and 1 which is used to calculate the rank score) in the output for benchmarking purposes?

Best regards,
Jonas

**Comment by jracle85** [comment]
Dear Jonas,

I've now published a new version (2.0.2) that allows outputting additional scores (option `-e` when running MixMHC2pred). These additional scores could be useful for example if one wants to integrate MixMHC2pred predictions with some other tools and want to have additional intermediate values.

Note however that I recommend using the final %Rank as the prediction score when the goal is to predict best candidate ligands/epitopes.

Indeed, there is be not a 1-1 correspondence between this %Rank and the "Score" as
* on one side, the final %Rank is the average of the %Rank obtained in 5 repetitions of the neural network (and the outputted "Score" is the average between these "Score" from the 5 repetitions;
* and on the other side, the %Rank is obtained by a transformation of the "Score" taking into account the peptide length distribution observed in MS.

Best regards,

Julien

**Comment by JonasNilsson1** [comment]
Dear Julien

Thank you for the update! Yes, the %rank score is of course the best way to select the optimal scoring peptide, but it's great to have the option of including the intermediate scores for calculating i.e. correlation values.

Best regards,
Jonas
